---
title: Açık Bilim.Türkiye
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
paginate: 10
markdown: kramdown
highlighter: rouge
permalink: none
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
description: Açık Bilim Topluluğu Türkiye
url: acikbilimtt.github.io
